server {
  listen 3000;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    try_files $uri =404;
  }

  location = / {
    try_files /index.html =404;
  }

  location = /admin_login {
    try_files /admin_login.html =404;
  }

  location = /official_login {
    try_files /official_login.html =404;
  }

  location = /beneficiary {
    try_files /beneficiary.html =404;
  }

  location = /beneficiary_register {
    try_files /beneficiary_register.html =404;
  }

  location = /peso_officer {
    try_files /peso_officer.html =404;
  }

  location = /peso_admin {
    try_files /peso_admin.html =404;
  }

  location = /cswdo_officer {
    try_files /cswdo_officer.html =404;
  }

  location = /cswdo_admin {
    try_files /cswdo_admin.html =404;
  }

  location = /evaluator {
    try_files /evaluator.html =404;
  }

  location ~* \.html$ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri.html =404;
  }
}
